### ISSUE TITLE
LaTeX ДСТУ

### ISSUE THREAD

**Issue by rostgw** [char-lie/latex-dstu#2]
Не могли бы Вы помочь с одной проблемой?
Недавно ознакомился с системой LaTeX, которая безусловно мне понравилась. Для вёрстки работ использовал пакет eskdx. С лабораторными работами проблем нет. Однако, для вёрстки курсовых, РГР, и других работ такого плана, мне нужно, чтобы в каждом новом разделе были заглавные рамки с своим отдельным шифром и надписью в ней. Можно ли это как-то реализовать?

**Comment by definability** [comment]
@rostgw, здравствуйте. Рамками я не занимался. Имеются ли картинки с примерами того, что хочется получить? Я бы посоветовал задать вопрос на форуме StackExchange, посвящённому TeX [tex.stackexchange.com](https://tex.stackexchange.com/)

**Comment by rostgw** [comment]
@char-lie, здравствуйте.
![2017-09-04 16-35-46 - - word](https://user-images.githubusercontent.com/31539001/30031359-b4b0f504-9199-11e7-9c48-4cbcebc46abd.png)
 Вот такое мне нужно получить. В одной работе.

**Comment by definability** [comment]
@rostgw, [Наложение основных надписей по ГОСТ 2.104 (рамок) на LaTeX документы](https://habrahabr.ru/post/163315/) &mdash; оно?

**Comment by rostgw** [comment]
Да, идея та же.

**Comment by definability** [comment]
@rostgw, к сожалению, ничем больше помочь не могу
